### ISSUE TITLE
Fails to compile with ESPHome 2026.3.0

### ISSUE THREAD

**Issue by jzucker2** [tuct/esphome-projects#15]
Getting an error with latest ESPHome 2026.3.0 release again:

```
src/esphome/components/levoit/binary_sensor/levoit_binary_sensor.cpp: In member function 'virtual void esphome::levoit::LevoitBinarySensor::setup()':
src/esphome/components/levoit/binary_sensor/levoit_binary_sensor.cpp:15:23: error: 'class esphome::levoit::LevoitBinarySensor' has no member named 'set_device_class'; did you mean 'get_device_class'?
   15 |                 this->set_device_class("battery");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/esphome/components/levoit/binary_sensor/levoit_binary_sensor.cpp:16:23: error: 'class esphome::levoit::LevoitBinarySensor' has no member named 'set_icon'; did you mean 'get_icon'?
   16 |                 this->set_icon("mdi:air-filter");
      |                       ^~~~~~~~
      |                       get_icon
*** [.pioenvs/livingroomairpurifierv1/src/esphome/components/levoit/binary_sensor/levoit_binary_sensor.cpp.o] Error 1
src/esphome/components/levoit/button/levoit_button.cpp: In member function 'virtual void esphome::levoit::LevoitButton::setup()':
src/esphome/components/levoit/button/levoit_button.cpp:18:23: error: 'class esphome::levoit::LevoitButton' has no member named 'set_entity_category'; did you mean 'get_entity_category'?
   18 |                 this->set_entity_category(EntityCategory::ENTITY_CATEGORY_CONFIG);
      |                       ^~~~~~~~~~~~~~~~~~~
      |                       get_entity_category
src/esphome/components/levoit/button/levoit_button.cpp:19:23: error: 'class esphome::levoit::LevoitButton' has no member named 'set_device_class'; did you mean 'get_device_class'?
   19 |                 this->set_device_class("reset");
      |                       ^~~~~~~~~~~~~~~~
      |                       get_device_class
src/esphome/components/levoit/button/levoit_button.cpp:20:23: error: 'class esphome::levoit::LevoitButton' has no member named 'set_icon'; did you mean 'get_icon'?
   20 |                 this->set_icon("mdi:air-filter");
      |                       ^~~~~~~~
      |                       get_icon
*** [.pioenvs/livingroomairpurifierv1/src/esphome/components/levoit/button/levoit_button.cpp.o] Error 1
========================= [FAILED] Took 121.61 seconds =========================
```

Why set the icon in the C++ code? Shouldn't the python handle that?
